var data = {
  status: "OK",
  results: [
        {
         num_results: 17,
         offset: 0,
         members: [
                {
                 id: "1",
                 team1: "U1",
                 team2: "U4",
                 location_first_name:"AJ",
                 location_last_name: "Katzenmaier",
                 date: "9/01",
                 hours: "9:30",
                 month: "S",
                 schedule: "a.m.",              
               },
                {
                 id: "2",
                 team1: "U3",
                 team2: "U2",
                 location_first_name: null,
                 location_last_name: "Greenbay",
                 date: "9/01",
                 hours: "1:00",
                 month: "S",
                 schedule: "p.m.", 
               },
                {
                 id: "3",
                 team1: "U5",
                 team2: "U6",
                 location_first_name: "Howard",
                 location_last_name: "Yeager",
                 date: "9/08",
                 hours: "9:30",
                 month: "S",
                 schedule: "a.m.",
               },
                {
                 id: "4",
                 team1: "U6",
                 team2: "U1",
                 location_first_name: "Marjorie",
                 location_last_name: "Hart",
                 date: "9/08",
                 hours: "1:00",
                 month: "S",
                 schedule: "p.m.",
               },
                {
                 id: "5",
                 team1: "U2",
                 team2: "U4",
                 location_first_name: "North",
                 location_last_name: null,
                 date: "9/15",
                 hours: "9:30",
                 month: "S",
                 schedule: "a.m.",
               },
                {
                 id: "6",
                 team1: "U3",
                 team2: "U5",
                 location_first_name: "AJ",
                 location_last_name: "Katzenmaier",
                 date: "9/15",
                 hours: "1:00",
                 month: "S",
                 schedule: "p.m.",
               },
                {
                 id: "7",
                 team1: "U1",
                 team2: "U3",
                 location_first_name: "South",
                 location_last_name: null,
                 date: "9/22",
                 hours: "9:30",
                 month: "S",
                 schedule: "a.m.",
               },
                {
                 id: "8",
                 team1: "U2",
                 team2: "U6",
                 location_first_name: "Howard",
                 location_last_name: "Yeager",
                 date: "9/22",
                 hours: "1:00",
                 month: "S",
                 schedule: "p.m.",
               },
                {
                 id: "9",
                 team1: "U4",
                 team2: "U5",
                 location_first_name: "Greenbay",
                 location_last_name: null,
                 date: "9/29",
                 hours: "9:30",
                 month: "S",
                 schedule: "a.m.",
               },
                {
                 id: "10",
                 team1: "U2",
                 team2: "U5",
                 location_first_name: "Marjorie",
                 location_last_name: "Hart",
                 date: "10/06",
                 hours: "9:30",
                 month: "O",
                 schedule: "a.m.",
               },
                {
                 id: "11",
                 team1: "U1",
                 team2: "U6",
                 location_first_name: "South",
                 location_last_name: null,
                 date: "10/06",
                 hours: "1:00",
                 month: "O",
                 schedule: "p.m.",
               },
                {
                 id: "12",
                 team1: "U3",
                 team2: "U4",
                 location_first_name: "Howard",
                 location_last_name: "Yeager",
                 date: "10/13",
                 hours: "9:30",
                 month: "O",
                 schedule: "a.m.",
               },
                {
                 id: "13",
                 team1: "U5",
                 team2: "U1",
                 location_first_name: "Greenbay",
                 location_last_name: null,
                 date: "10/13",
                 hours: "1:00",
                 month: "O",
                 schedule: "p.m.",
               },
                {
                 id: "14",
                 team1: "U6",
                 team2: "U3",
                 location_first_name: "North",
                 location_last_name: null,
                 date: "10/20",
                 hours: "9:30",
                 month: "O",
                 schedule: "a.m.",
               },
                {
                 id: "15",
                 team1: "U2",
                 team2: "U4",
                 location_first_name: "Marjorie",
                 location_last_name: "Hart",
                 date: "10/20",
                 hours: "1:00",
                 month: "O",
                 schedule: "p.m.",
               },
                {
                 id: "16",
                 team1: "U3",
                 team2: "U1",
                 location_first_name: "AJ",
                 location_last_name: "Katzenmaier",
                 date: "10/27",
                 hours: "9:30",
                 month: "O",
                 schedule: "a.m.",
               },
                {
                 id: "17",
                 team1: "U5",
                 team2: "U6",
                 location_first_name: "Howard",
                 location_last_name: "Yeager",
                 date: "10/27",
                 hours: "1:00",
                 month: "O",
                 schedule: "p.m.",
               }
            ]
        }
   ]
}
